### ISSUE TITLE
RuntimeError: [KeOps] Cuda error.

### ISSUE THREAD

**Issue by ZkzMMDC** [getkeops/keops#361]
python 3.8 ,cuda 11.2,  GPU RTX4090

When I run the following test “pykeops.test_torch_bindings() ” to make sure Keops work:

[KeOps] Generating code for Sum_Reduction reduction (with parameters 1) of formula Sum((a-b)**2) with a=Var(0,3,0), b=Var(1,3,1) ... OK

[KeOps] error: cuModuleLoadDataEx(&module, target, 0, NULL, NULL) failed with error CUDA_ERROR_INVALID_IMAGE

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zkz/anaconda3/envs/robot/lib/python3.8/site-packages/pykeops/torch/test_install.py", line 21, in test_torch_bindings
    my_conv(x, y).view(-1), torch.tensor(expected_res).type(torch.float32)
  File "/home/zkz/anaconda3/envs/robot/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py", line 687, in __call__
    out = GenredAutograd_fun(params, *args)
  File "/home/zkz/anaconda3/envs/robot/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py", line 271, in forward
    outputs = GenredAutograd_base._forward(*inputs)
  File "/home/zkz/anaconda3/envs/robot/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py", line 91, in _forward
    myconv = keops_binder["nvrtc" if tagCPUGPU else "cpp"](
  File "/home/zkz/anaconda3/envs/robot/lib/python3.8/site-packages/keopscore/utils/Cache.py", line 91, in __call__
    obj = self.cls(*args)
  File "/home/zkz/anaconda3/envs/robot/lib/python3.8/site-packages/pykeops/common/keops_io/LoadKeOps_nvrtc.py", line 16, in __init__
    super().__init__(*args, fast_init=fast_init)
  File "/home/zkz/anaconda3/envs/robot/lib/python3.8/site-packages/pykeops/common/keops_io/LoadKeOps.py", line 31, in __init__
    self.init_phase2()
  File "/home/zkz/anaconda3/envs/robot/lib/python3.8/site-packages/pykeops/common/keops_io/LoadKeOps_nvrtc.py", line 29, in init_phase2
    self.launch_keops = pykeops_nvrtc.KeOps_module_float(
RuntimeError: [KeOps] Cuda error.

**Comment by wang-jh18-SVM** [comment]
I'm encountering the same `CUDA_ERROR_INVALID_IMAGE` error when running KeOps with pytorch bindings. Below are the steps to reproduce the error, the full error message, and my system information.

**Steps to Reproduce:**

```python
import pykeops
pykeops.clean_pykeops()
pykeops.test_torch_bindings()
```

**Error Message:**

```
[KeOps] /root/.cache/keops2.2.2/Linux_autodl-container-758f438c9a-33381152_5.15.0-91-generic_p3.8.18 has been cleaned.
[KeOps] Compiling cuda jit compiler engine ... OK
[pyKeOps] Compiling nvrtc binder for python ... OK
[KeOps] Generating code for Sum_Reduction reduction (with parameters 1) of formula Sum((a-b)**2) with a=Var(0,3,0), b=Var(1,3,1) ... OK

[KeOps] error: cuModuleLoadDataEx(&module, target, 0, NULL, NULL) failed with error CUDA_ERROR_INVALID_IMAGE

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/pykeops/torch/test_install.py", line 21, in test_torch_bindings
    my_conv(x, y).view(-1), torch.tensor(expected_res).type(torch.float32)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py", line 687, in __call__
    out = GenredAutograd_fun(params, *args)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py", line 271, in forward
    outputs = GenredAutograd_base._forward(*inputs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py", line 91, in _forward
    myconv = keops_binder["nvrtc" if tagCPUGPU else "cpp"](
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/keopscore/utils/Cache.py", line 91, in __call__
    obj = self.cls(*args)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/pykeops/common/keops_io/LoadKeOps_nvrtc.py", line 16, in __init__
    super().__init__(*args, fast_init=fast_init)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/pykeops/common/keops_io/LoadKeOps.py", line 31, in __init__
    self.init_phase2()
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/pykeops/common/keops_io/LoadKeOps_nvrtc.py", line 29, in init_phase2
    self.launch_keops = pykeops_nvrtc.KeOps_module_float(
RuntimeError: [KeOps] Cuda error.
```

The above error suggests there might be an issue with the CUDA image. I've made sure to clean the KeOps cache before testing the torch bindings.

**System Information:**

- GPU: RTX 4090
- CUDA Version: 11.8 (from `nvcc -V`)
- Relevant Installed Packages:
  - cudatoolkit: 11.6.2
  - pykeops: 2.2.2 (from PyPI)
  - pytorch: 1.12.0 with CUDA 11.6 support
  - python: 3.8.18

**Full Conda List:**

```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
blas                      1.0                         mkl    conda-forge
brotli-python             1.1.0            py38h17151c0_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
cudatoolkit               11.6.2              hfc3e2af_13    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.10.4               h0708190_1    conda-forge
gmp                       6.3.0                h59595ed_1    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
intel-openmp              2023.1.0         hdb19cb5_46306    defaults
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
keopscore                 2.2.2                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0           1_h86c2bf4_netlib    conda-forge
libcblas                  3.9.0           5_h92ddd45_netlib    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libhwloc                  2.9.1                hd6dc26d_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           5_h92ddd45_netlib    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxml2                   2.10.4               hf1b16e4_1    defaults
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mkl                       2023.1.0         h213fc3f_46344    defaults
ncurses                   6.4                  h6a678d5_0    defaults
nettle                    3.6                  he412f7d_0    conda-forge
numpy                     1.24.4           py38h59b608b_0    conda-forge
olefile                   0.47               pyhd8ed1ab_0    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   3.2.1                hd590300_0    conda-forge
pillow                    8.2.0            py38ha0e1e83_1    conda-forge
pip                       23.3.1           py38h06a4308_0    defaults
pybind11                  2.11.1                   pypi_0    pypi
pykeops                   2.2.2                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.18               h955ad1f_0    defaults
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.12.0          py3.8_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
readline                  8.2                  h5eee18b_0    defaults
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
setuptools                68.2.2           py38h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tbb                       2021.9.0             hf52228f_0    conda-forge
tk                        8.6.12               h1ccaba5_0    defaults
torchvision               0.13.0               py38_cu116    pytorch
typing_extensions         4.10.0             pyha770c72_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2           py38h06a4308_0    defaults
xz                        5.4.6                h5eee18b_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstd                      1.5.0                ha95c52a_0    conda-forge
```

Has anyone else experienced a similar issue or can provide insight into what might be causing the `CUDA_ERROR_INVALID_IMAGE` error with KeOps on an RTX 4090 GPU?

**Comment by jeanfeydy** [comment]
Hi @ZkzMMDC , @wang-jh18-SVM ,

Thanks for your interest in our library, and the detailed reports.
I don't have a RTX4090 at hand to try this myself, but I'll be very surprised if this turns out to be a hardware issue. KeOps runs fine on all the Nvidia GPUs that we've had access to since 2017, it does not rely on niche instruction sets.

As far as I can tell, the most likely issue here is that in @wang-jh18-SVM 's report, `cudatoolkit==11.6.2` while `nvcc==1.8`: **the vast majority of KeOps installation issues happen on systems where several versions of CUDA are available, and we somehow mix up the paths**.

Could you maybe:
- Install `nvcc == 11.6.2` in your conda environment, maybe via e.g. `conda install -y -c nvidia/label/cuda-11.6.2 cuda`? Our [Dockerfile](https://github.com/getkeops/keops/blob/main/Dockerfile) provides a good reference for a fully functional setup.
- Try our [Docker image](http://kernel-operations.io/keops/python/installation.html#using-docker-or-singularity) (`docker pull getkeops/keops-full:latest`), just to make sure that this is not a harware problem?

Best regards,
Jean

**Comment by Yangr116** [comment]
The same issue, I use the pykeops docker.

**Comment by soulofxin** [comment]
> When I run the following test “pykeops.test_torch_bindings() ” to make sure Keops work:

have you solved that problem?

**Comment by wang-jh18-SVM** [comment]
Hi, I still don't know why, but when I install pytorch with pip rather than conda, it works.

**Comment by akhilrkurup** [comment]
Facing the same issue even when using the versions of libraries as found in the dockerfile. Anyone found a solution ?

**Comment by Classicalqy** [comment]
Facing the same issue😭

**Comment by ljwwwiop** [comment]
I successfully compiled and configured KeOps on a single RTX 4090 GPU using 

pip install pykeops==2.2.3.

To run it properly, I needed to set the LIBRARY_PATH environment variable beforehand. After that, everything worked smoothly.

import os
os.environ['LIBRARY_PATH'] = '/usr/local/cuda-11.8/lib64'

**Comment by ryanliu30** [comment]
I encountered the same issue: 
```
import pykeops
pykeops.clean_pykeops()
pykeops.test_torch_bindings()
```
The output of tests:
```
[KeOps] Generating code for Sum_Reduction reduction (with parameters 1) of formula Sum((a-b)**2) with a=Var(0,3,0), b=Var(1,3,1) ... OK

[KeOps] error: cuModuleLoadDataEx(&module, target, 0, NULL, NULL) failed with error CUDA_ERROR_INVALID_IMAGE

Traceback (most recent call last):
  File "<python-input-1>", line 3, in <module>
    pykeops.test_torch_bindings()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/pykeops/torch/test_install.py", line 21, in test_torch_bindings
    my_conv(x, y).view(-1), torch.tensor(expected_res).type(torch.float32)
    ~~~~~~~^^^^^^
  File "/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/pykeops/torch/generic/generic_red.py", line 693, in __call__
    out = GenredAutograd_fun(params, *args)
  File "/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/pykeops/torch/generic/generic_red.py", line 383, in GenredAutograd_fun
    return GenredAutograd.apply(*inputs)[0]
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/torch/autograd/function.py", line 576, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/pykeops/torch/generic/generic_red.py", line 291, in forward
    return GenredAutograd_base._forward(*inputs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/pykeops/torch/generic/generic_red.py", line 91, in _forward
    myconv = keops_binder["nvrtc" if tagCPUGPU else "cpp"](
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        tagCPUGPU,
        ^^^^^^^^^^
    ...<9 lines>...
        params.optional_flags,
        ^^^^^^^^^^^^^^^^^^^^^^
    ).import_module()
    ^
  File "/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/keopscore/utils/Cache.py", line 92, in __call__
    obj = self.cls(*args)
  File "/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/pykeops/common/keops_io/LoadKeOps_nvrtc.py", line 16, in __init__
    super().__init__(*args, fast_init=fast_init)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/pykeops/common/keops_io/LoadKeOps.py", line 31, in __init__
    self.init_phase2()
    ~~~~~~~~~~~~~~~~^^
  File "/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/pykeops/common/keops_io/LoadKeOps_nvrtc.py", line 29, in init_phase2
    self.launch_keops = pykeops_nvrtc.KeOps_module_float(
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.params.device_id_request,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.params.nargs,
        ^^^^^^^^^^^^^^^^^^
        self.params.low_level_code_file,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
RuntimeError: [KeOps] Cuda error.
```

Output of check health:

```

Platform Information
============================================================
Operating System: Linux Ubuntu 20.04
Python Version: 3.13.7
Environment Type: conda (neuralop)

Relevant Environment Variables
------------------------------------------------------------
CONDA_DEFAULT_ENV = neuralop
VIRTUAL_ENV is not set
PATH = /root/miniconda3/envs/neuralop/bin:/root/miniconda3/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PYTHONPATH is not set
CXX is not set

Base Configuration
------------------------------------------------------------
Base Directory Path: /root/miniconda3/envs/neuralop/lib/python3.13/site-packages/keopscore ✅
Bindings Source Directory: /root/miniconda3/envs/neuralop/lib/python3.13/site-packages/keopscore ✅
KeOps Cache Folder: /root/.cache/keops2.3 ✅
Default Build Folder Name: Linux_1b3e0c91d9bd_6.8.0-59-generic_p3.13.7
Default Build Path: /root/.cache/keops2.3/Linux_1b3e0c91d9bd_6.8.0-59-generic_p3.13.7 ✅
JIT Binary Path: /root/.cache/keops2.3/Linux_1b3e0c91d9bd_6.8.0-59-generic_p3.13.7 ✅
Disable Pragma Unrolls: Enabled ✅
Compile Options:  -shared -fPIC -O3 -std=c++11
C++ Compiler Flags:   -shared -fPIC -O3 -std=c++11 -I/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/keopscore/include -I/root/miniconda3/envs/neuralop/lib/python3.13/site-packages/keopscore -fopenmp -flto=auto

Relevant Environment Variables:
KEOPS_CACHE_FOLDER is not set
CXXFLAGS is not set

CUDA Support
------------------------------------------------------------
CUDA Support: Enabled ✅
Libcuda Path: /usr/lib/x86_64-linux-gnu
Libnvrtc Path: /usr/local/cuda/targets/x86_64-linux/lib
CUDA Version: 11070
Number of GPUs: 1
GPU Compile Flags: -DMAXIDGPU=0 -DMAXTHREADSPERBLOCK0=1024 -DSHAREDMEMPERBLOCK0=49152 
CUDA Include Path: /usr/local/cuda/include

Relevant Environment Variables:
CUDA_VISIBLE_DEVICES is not set
CUDA_PATH is not set

OpenMP Support
------------------------------------------------------------
OpenMP Support: Enabled ✅
OpenMP Library Path: /root/miniconda3/envs/neuralop/lib/libgomp.so.1
C++ Compiler: g++

Relevant Environment Variables:
OMP_PATH is not set
```

**Comment by rigmor2002** [comment]
Have you solved this problem? I'm facing the same issue

**Comment by biomolecule** [comment]
# My Solution for CUDA Error on Multi-CUDA Systems

## Problem

When installing PyKeOps on systems with multiple CUDA versions, the official installation guide fails with:

```
RuntimeError: [KeOps] Cuda error.
CUDA_ERROR_UNSUPPORTED_PTX_VERSION
```

or

```
RuntimeError: [KeOps] Cuda error.
CUDA_ERROR_INVALID_IMAGE
```

This happens because PyKeOps detects and loads the wrong CUDA version when multiple versions are installed on the system.

## Root Cause

PyKeOps uses Python's `ctypes.util.find_library()` to locate CUDA libraries. On systems with multiple CUDA installations (e.g., CUDA 13.1 in `/usr/local/cuda/` and CUDA 12.x in `/lib/x86_64-linux-gnu/`), `find_library()` returns the highest version number by default.

For example:
- System has: CUDA 13.1 (`/usr/local/cuda/`) and CUDA 12.0 (`/lib/x86_64-linux-gnu/`)
- PyTorch uses: CUDA 12.1 (installed via pip)
- PyKeOps loads: CUDA 13.1 NVRTC library
- **Result**: Version mismatch → PTX compilation error

The NVRTC 13.1 generates PTX code that is incompatible with the CUDA driver/runtime used by PyTorch 12.1.

## Solution

Modify PyKeOps to prefer CUDA 12.x libraries over newer versions for better compatibility. Simpily, add CUDA 12.0 path (`/lib/x86_64-linux-gnu/`) before CUDA 13.1 (`/usr/local/cuda/`).

### Step 1: Install PyKeOps normally

```bash
conda create -n pykeops python=3.9 -y
conda activate pykeops
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
pip install pykeops
```

### Step 2: Apply the patch

Edit the file:
```
<your_conda_env>/lib/python3.9/site-packages/keopscore/config/cuda.py
```

**Find the `_try_load_library` method** (around line 64) and replace it with:

```python
def _try_load_library(self, lib_name):
    """
    Attempt to locate and load libraties.
    Returns:
        success (bool): True if the library was found and loaded.
        abspath (str): Absolute path to the loaded library if success==True, else "".
        error_msg (str): Contains error details if success==False, else "".
    """
    # For nvrtc and cudart, prefer version 12.x over 13.x for compatibility
    if lib_name in ['nvrtc', 'cudart']:
        # Try to find CUDA 12.x version first
        possible_paths = [
            '/lib/x86_64-linux-gnu/lib' + lib_name + '.so.12',
            '/lib/x86_64-linux-gnu/lib' + lib_name + '.so',
            '/usr/lib/x86_64-linux-gnu/lib' + lib_name + '.so.12',
            '/usr/lib/x86_64-linux-gnu/lib' + lib_name + '.so',
        ]
        
        found_path = None
        for path in possible_paths:
            if os.path.exists(path):
                found_path = path
                break
        
        # Fall back to find_library if no CUDA 12.x found
        if not found_path:
            found_path = find_library(lib_name)
    else:
        # Find library using standard method
        found_path = find_library(lib_name)
    
    if not found_path:
        return (False, "", f"Library '{lib_name}' not found on this system.")

    # Try to load it
    try:
        lib_handle = CDLL(found_path, mode=RTLD_GLOBAL)
    except OSError as e:
        return (False, "", f"Failed to load library '{lib_name}': {e}")

    class LINKMAP(Structure):
        _fields_ = [("l_addr", c_void_p), ("l_name", c_char_p)]

    try:
        # Attempt to load libdl to use dlinfo
        libdl_path = find_library("dl")
        if not libdl_path:
            # If we can't find libdl, we can't do dlinfo; fallback
            return (True, found_path, "")

        libdl = CDLL(libdl_path)
        dlinfo = libdl.dlinfo
        dlinfo.argtypes = (c_void_p, c_int, c_void_p)
        dlinfo.restype = c_int

        lmptr = c_void_p()
        # RTLD_DI_LINKMAP = 2
        result = dlinfo(lib_handle._handle, 2, byref(lmptr))
        if result != 0:
            # dlinfo call failed, fallback
            return (True, found_path, "")

        abspath_bytes = cast(lmptr, POINTER(LINKMAP)).contents.l_name
        abspath_str = abspath_bytes.decode("utf-8")
        if abspath_str:
            return (True, abspath_str, "")
        else:
            return (True, found_path, "")
    except Exception as err:
        # If anything goes wrong, fallback to found_path
        return (True, found_path, "")
```

**Find the `get_cuda_version` method** (around line 270) and replace it with:

```python
def get_cuda_version(self, out_type="single_value"):
    if not self._use_cuda:
        self.cuda_version = None
        return None
    try:
        # Prefer CUDA 12.x version for compatibility
        possible_paths = [
            '/lib/x86_64-linux-gnu/libcudart.so.12',
            '/lib/x86_64-linux-gnu/libcudart.so',
            '/usr/lib/x86_64-linux-gnu/libcudart.so.12',
            '/usr/lib/x86_64-linux-gnu/libcudart.so',
        ]
        
        libcudart_path = None
        for path in possible_paths:
            if os.path.exists(path):
                libcudart_path = path
                break
        
        # Fall back to find_library if no CUDA 12.x found
        if not libcudart_path:
            libcudart_path = find_library("cudart")
        
        if not libcudart_path:
            self.cuda_version = None
            return None

        libcudart = ctypes.CDLL(libcudart_path)
        cuda_version = ctypes.c_int()
        libcudart.cudaRuntimeGetVersion(ctypes.byref(cuda_version))
        cuda_version_value = int(cuda_version.value)

        if out_type == "single_value":
            self.cuda_version = cuda_version_value
            return cuda_version_value

        major = cuda_version_value // 1000
        minor = (cuda_version_value % 1000) // 10

        if out_type == "major,minor":
            return major, minor
        elif out_type == "string":
            return f"{major}.{minor}"
    except Exception as e:
        KeOps_Warning(f"Could not determine CUDA version: {e}")
        self.cuda_version = None
        return None
```

### Step 3: Clear cache and test

```bash
rm -rf ~/.cache/keops*
python -c "import pykeops; pykeops.test_numpy_bindings()"
python -c "import pykeops; pykeops.test_torch_bindings()"
```

Expected output:
```
pyKeOps with numpy bindings is working!
pyKeOps with torch bindings is working!
```

## Why This Works

The patch modifies PyKeOps to explicitly search for CUDA 12.x libraries in common system paths before falling back to the default `find_library()` behavior. This ensures:

1. **Consistent CUDA version**: PyKeOps uses the same CUDA version family as PyTorch (12.x)
2. **PTX compatibility**: NVRTC 12.x generates PTX code compatible with CUDA drivers supporting 12.x+
3. **No system changes**: The fix is isolated to the PyKeOps environment, doesn't affect other programs

## Tested Environment

- **OS**: Ubuntu 24.04
- **Python**: 3.9
- **System CUDA**: 13.1 (`/usr/local/cuda-13.1`)
- **Available CUDA**: 12.0 (`/lib/x86_64-linux-gnu/`)
- **PyTorch**: 2.5.1+cu121
- **PyKeOps**: 2.3
- **GPU**: Tesla V100 (Compute Capability 7.0)

## Notes

- If your system doesn't have CUDA 12.x libraries in `/lib/x86_64-linux-gnu/`, install them via your package manager (e.g., `sudo apt install nvidia-cuda-toolkit`)
- The patch gracefully falls back to the original behavior if CUDA 12.x is not found
- This solution works for any multi-CUDA setup where you need PyKeOps to use a specific CUDA version
